// English translations of all data content

export const publicationsEn = [
  {
    id: 1,
    slug: "krisis-nilai-tukar-ketahanan-pangan",
    title: "Indonesia's Exchange Rate Crisis as a Reminder for Food Security",
    category: "Brief",
    date: "June 2026",
    description: "Analysis of the exchange rate crisis impact on the national food security system and short-term adaptation strategies.",
    tags: ["food security", "policy", "economics"],
    image: "https://images.unsplash.com/photo-1611735341450-74d61e660ad2?w=600&q=80",
    researchAreas: ["sustainable-food-system"],
    topics: ["food-security", "governance"],
  },
  {
    id: 2,
    slug: "pengelolaan-air-gambut-kelapa-berkelanjutan",
    title: "Traditional Water Management in Peatlands for Sustainable Coconut Farming",
    category: "Research Article",
    date: "May 2026",
    description: "A study of local water management practices in Kalimantan peatlands supporting sustainable coconut agriculture.",
    tags: ["peatland", "water", "agriculture"],
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80",
    researchAreas: ["peatland-agriculture-sustainability", "coconut-research-center"],
    topics: ["suboptimal-land", "landscape", "agriculture"],
  },
  {
    id: 3,
    slug: "laporan-tahunan-2025-keberlanjutan-pangan",
    title: "Annual Report 2025: Collaborative Pathways Toward Food Sustainability",
    category: "Annual Report",
    date: "April 2026",
    description: "TJF's 2025 annual report summarizing achievements, learnings, and the organization's strategic direction.",
    tags: ["annual report", "organization"],
    image: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600&q=80",
    researchAreas: ["sustainable-food-system", "peatland-agriculture-sustainability", "coconut-research-center", "coastal-agriculture-water-management"],
    topics: ["food-security", "agriculture", "suboptimal-land", "livelihood", "landscape", "governance"],
  },
  {
    id: 4,
    slug: "potensi-lahan-rawa-pasang-surut",
    title: "Potential of Tidal Swampland as a Future Food Source",
    category: "Research Article",
    date: "March 2026",
    description: "In-depth research on optimizing tidal swampland in South Sumatra for rice production.",
    tags: ["swampland", "rice", "Sumatra"],
    image: "https://images.unsplash.com/photo-1536408157428-1e2ede34fef3?w=600&q=80",
    researchAreas: ["coastal-agriculture-water-management"],
    topics: ["suboptimal-land", "food-security", "agriculture"],
  },
  {
    id: 5,
    slug: "panduan-pertanian-regeneratif-lahan-suboptimal",
    title: "Practical Guide to Regenerative Agriculture on Suboptimal Land",
    category: "Book",
    date: "February 2026",
    description: "A comprehensive handbook for farmers and extension workers on implementing regenerative agriculture on marginal land.",
    tags: ["regenerative agriculture", "guide", "farmers"],
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80",
    researchAreas: ["sustainable-food-system"],
    topics: ["agriculture", "livelihood", "suboptimal-land"],
  },
  {
    id: 6,
    slug: "dampak-perubahan-iklim-lahan-gambut",
    title: "Climate Change Impact on Peatland Productivity in Indonesia",
    category: "Research Article",
    date: "January 2026",
    description: "A longitudinal study of climate change impacts on productivity and sustainability of peatland management.",
    tags: ["climate change", "peatland", "productivity"],
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&q=80",
    researchAreas: ["peatland-agriculture-sustainability"],
    topics: ["suboptimal-land", "landscape"],
  },
  {
    id: 7,
    slug: "inovasi-varietas-padi-adaptif",
    title: "Adaptive Rice Variety Innovation for Suboptimal Land",
    category: "Research Article",
    date: "December 2025",
    description: "Results of developing rice varieties adaptive to suboptimal land conditions and climate change.",
    tags: ["rice variety", "innovation", "adaptation"],
    image: "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=600&q=80",
    researchAreas: ["sustainable-food-system"],
    topics: ["agriculture", "food-security", "suboptimal-land"],
  },
  {
    id: 8,
    slug: "ekosistem-pengetahuan-ketahanan-pangan",
    title: "Knowledge Ecosystem for Food Security: The Role of Knowledge Intermediaries",
    category: "Brief",
    date: "November 2025",
    description: "A review of the role of knowledge intermediary organizations in building sustainable food security ecosystems.",
    tags: ["knowledge", "ecosystem", "intermediary"],
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&q=80",
    researchAreas: ["sustainable-food-system"],
    topics: ["food-security", "governance"],
  },
];

export const initiativesEn = [
  {
    id: 1,
    title: "Sustainable Peatland Agriculture",
    slug: "pertanian-gambut-berkelanjutan",
    tagline: "Restoring peatland function as an ecological food asset",
    description: "This program develops farming models aligned with peat ecosystems, combining local wisdom and scientific innovation for productive agriculture while maintaining peatland hydrological function.",
    focus: [
      "Rewetting of degraded peatlands",
      "Development of eco-friendly peatland commodities",
      "Strengthening peatland farmer institutions",
    ],
    color: "green",
    icon: "🌿",
    stats: { projects: 42, communities: 18, provinces: 5 },
    image: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80",
    topics: ["suboptimal-land", "landscape", "livelihood"],
  },
  {
    id: 2,
    title: "Suboptimal Land Agriculture",
    slug: "pertanian-lahan-suboptimal",
    tagline: "Unlocking the potential of marginal land for the future of food",
    description: "A research and dissemination initiative exploring the potential of suboptimal lands — swamps, tidal flats, dryland, and acidic soils — as future food sources through technological innovation and participatory approaches.",
    focus: [
      "Crop adaptation research on suboptimal land",
      "Low-input technology development",
      "Dissemination of best practices for marginal land farming",
    ],
    color: "blue",
    icon: "🌾",
    stats: { projects: 35, communities: 24, provinces: 8 },
    image: "https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=800&q=80",
    topics: ["suboptimal-land", "agriculture", "food-security"],
  },
  {
    id: 3,
    title: "Writing Collaboration",
    slug: "kolaborasi-menulis",
    tagline: "Building a shared narrative about Indonesia's food future",
    description: "A collaboration platform connecting researchers, field practitioners, farmers, and policymakers to jointly produce relevant and actionable knowledge.",
    focus: [
      "Writer residency program",
      "Webinar and discussion series",
      "Cross-actor collaborative publishing",
    ],
    color: "amber",
    icon: "✍️",
    stats: { projects: 28, communities: 60, provinces: 15 },
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    topics: ["governance", "livelihood", "food-security"],
  },
  {
    id: 4,
    title: "Food Resilience & Sustainability Center",
    slug: "pusat-ketahanan-pangan",
    tagline: "Bridging research and policy for a resilient food system",
    description: "A knowledge hub connecting research data, field learnings, and policy analysis to drive transformation of Indonesia's food system toward long-term resilience.",
    focus: [
      "Food policy analysis and advocacy",
      "Food system monitoring and evaluation",
      "Multi-stakeholder knowledge networks",
    ],
    color: "blue",
    icon: "🏛️",
    stats: { projects: 19, communities: 40, provinces: 12 },
    image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&q=80",
    topics: ["food-security", "governance"],
  },
];

export const newsItemsEn = [
  {
    id: 1,
    slug: "tjf-luncurkan-platform-digital-lahan-suboptimal",
    tags: ["digital platform", "suboptimal land", "technology", "knowledge"],
    title: "TJF Launches Digital Knowledge Platform for Suboptimal Land",
    category: "Organization News",
    date: "June 10, 2026",
    excerpt: "Tay Juhana Foundation officially launched an integrated digital platform as a suboptimal land knowledge hub accessible to all stakeholders.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    topics: ["suboptimal-land", "governance"],
    content: [
      "Tay Juhana Foundation (TJF) officially launched its integrated digital platform on June 10, 2026 — Indonesia's first comprehensive knowledge hub dedicated to suboptimal land agriculture. The platform brings together thousands of research documents, practical field guides, and policy databases, all freely accessible to researchers, farmers, extension workers, and policymakers across the archipelago.",
      "The platform was developed over two years in partnership with local technology companies and now hosts over 500 scientific publications, 120 agricultural tutorial videos, and an online consultation feature connecting users directly with TJF experts. A key feature is a location-based recommendation system that helps farmers find best practices matched to their specific land conditions and local climate.",
      "According to TJF's Program Director, this launch represents a long-term commitment to democratizing access to agricultural knowledge. \"We want to ensure that a farmer in remote Kalimantan has the same access to scientific knowledge as a researcher in a major city,\" she said at the launch ceremony. The platform is targeting 50,000 active users in its first year of operation.",
    ],
  },
  {
    id: 2,
    slug: "riset-tjf-diadopsi-kebijakan-pertanian-nasional",
    tags: ["policy", "research", "peatland", "national agriculture"],
    title: "TJF Research Adopted in National Agricultural Policy",
    category: "Impact",
    date: "May 28, 2026",
    excerpt: "Indonesia's Ministry of Agriculture adopted recommendations from TJF's peatland management research in formulating the 2026–2030 national agricultural policy.",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    topics: ["governance", "agriculture", "suboptimal-land"],
    content: [
      "In a historic milestone for Indonesian agricultural research, the Ministry of Agriculture of the Republic of Indonesia has officially adopted a set of policy recommendations drawn from Tay Juhana Foundation's eight years of research on peatland management. The decision is enshrined in a Ministerial Regulation published in late May 2026.",
      "The adopted recommendations cover water management standards in peatlands, planting protocols for peatland-friendly commodities, and incentive mechanisms for farmers practicing sustainable agriculture. TJF conducted in-depth field studies across five provinces with the largest peatland ecosystems — Central Kalimantan, West Kalimantan, Riau, Jambi, and West Papua — from 2018 to 2025.",
      "The policy impact is estimated to reach more than 4.2 million hectares of peatland managed by farmers and agricultural cooperatives. The Head of the Ministry's Research and Development Agency noted that collaboration between independent think tanks like TJF and government ministries is a model worth replicating across other sectors. TJF has committed to supporting the implementation of these policies through training and field monitoring programs.",
    ],
  },
  {
    id: 3,
    slug: "workshop-nasional-inovasi-pertanian-lahan-suboptimal-2026",
    tags: ["workshop", "innovation", "suboptimal land", "community"],
    title: "National Workshop: Suboptimal Land Agriculture Innovation 2026",
    category: "Events",
    date: "May 15, 2026",
    excerpt: "TJF hosted a national workshop bringing together 200 researchers, farmers, and policymakers from 15 provinces to share innovations in suboptimal land agriculture.",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    topics: ["suboptimal-land", "agriculture", "livelihood"],
    content: [
      "For three full days, May 15–17, 2026, a Jakarta conference center became the hub for over 200 participants from 15 provinces at the National Workshop on Suboptimal Land Agriculture Innovation, organized by Tay Juhana Foundation. The event marked TJF's largest-ever convening, bringing together a unique mix of academic researchers, innovative farmers, field extension workers, and policy stakeholders.",
      "Highlight sessions included live demonstrations of precision agriculture technology for tidal swampland, group discussions on crop variety adaptation to marginal land conditions, and an innovation pitch session where 20 farmers presented their creative solutions to a panel of investors and policymakers. Four of the 20 innovations received initial funding commitments for further development.",
      "The Head of South Kalimantan's Agriculture Office, speaking as a keynote speaker, highlighted the importance of such forums in accelerating the transfer of knowledge from laboratory to field. The workshop closed with the signing of memoranda of understanding between TJF and three agricultural universities for five-year collaborative research programs.",
    ],
  },
  {
    id: 4,
    slug: "petani-gambut-kalimantan-peningkatan-hasil-40-persen",
    tags: ["peatland", "kalimantan", "productivity", "water management"],
    title: "Kalimantan Peatland Farmers Achieve 40% Yield Increase with TJF Method",
    category: "Impact Story",
    date: "May 2, 2026",
    excerpt: "A peatland farming community in Central Kalimantan increased their harvest by up to 40% after implementing TJF's sustainable farming methods.",
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
    topics: ["suboptimal-land", "livelihood", "landscape", "food-security"],
    content: [
      "In Sei Ahas village, Kapuas Regency, Central Kalimantan, Suroso and 47 neighboring farmers now harvest rice twice a year — something they considered impossible just three years ago. Thanks to intensive field support from Tay Juhana Foundation's team since 2023, this community has increased average yields from 2.1 tons per hectare to 2.9 tons — an increase of nearly 40%.",
      "The key to this success lies in a water management system developed by TJF. The \"water table management\" method, adapted to Central Kalimantan's tropical peatlands, allows farmers to maintain groundwater levels at an optimal point — wet enough to prevent peat fires, yet dry enough for healthy crop growth. The system is equipped with simple monitoring stations operated by the farmers themselves.",
      "\"Before, we feared the peatlands would burn every dry season. Now we have control,\" said Suroso. Beyond productivity gains, the community also reported a 25% reduction in production costs due to more efficient use of chemical fertilizers. TJF plans to replicate this model in 12 other peatland villages across Central and South Kalimantan by the end of 2026.",
    ],
  },
  {
    id: 5,
    slug: "tjf-rilis-panduan-pengelolaan-lahan-gambut",
    tags: ["guide", "peatland", "farmers", "publication"],
    title: "TJF Releases Practical Peatland Management Guide for Farmers",
    category: "Publication",
    date: "April 20, 2026",
    excerpt: "A practical peatland management guide written in accessible language is now freely available for download.",
    image: "https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?w=800&q=80",
    topics: ["suboptimal-land", "landscape", "livelihood"],
    content: [
      "Tay Juhana Foundation has released its long-awaited peatland management guide for Indonesia's farming community. The 84-page document is written in plain Indonesian, free of academic jargon, and is illustrated with full-color diagrams and field photographs that make the content accessible even to farmers with limited formal literacy.",
      "The guide covers six main areas: understanding peatland characteristics, techniques for measuring and managing groundwater levels, selecting the right commodities, optimal planting schedules, managing peatland-specific pests and diseases, and fire prevention steps. Each chapter includes a practical checklist that farmers can use directly in the field.",
      "The guide is available as a printed copy — orderable free of charge through the Agriculture Department offices in 12 TJF partner districts — and as a digital download through TJF's digital platform. Within the first two weeks of its launch, the guide was downloaded more than 8,000 times and ordered in print format by 230 farmer groups across Indonesia.",
    ],
  },
  {
    id: 6,
    slug: "kolaborasi-tjf-brin-varietas-padi-adaptif",
    tags: ["rice variety", "BRIN", "collaboration", "suboptimal land"],
    title: "TJF & BRIN Collaboration Produces Adaptive Rice Varieties",
    category: "Research",
    date: "April 8, 2026",
    excerpt: "The joint effort between TJF and BRIN has successfully developed two new rice varieties adapted to swampland conditions.",
    image: "https://images.unsplash.com/photo-1559715745-e1b33a271c8f?w=800&q=80",
    topics: ["agriculture", "food-security", "suboptimal-land"],
    content: [
      "After four years of intensive research, the collaboration between Tay Juhana Foundation and the National Research and Innovation Agency (BRIN) has finally borne fruit: two new rice varieties specifically developed for Indonesia's swamp and tidal land conditions. Both varieties — named \"TJF-Rawa 1\" and \"TJF-Rawa 2\" — have undergone extensive field trials in South Sumatra, South Kalimantan, and South Sulawesi.",
      "TJF-Rawa 1 excels in high-salinity conditions such as those found in coastal tidal areas, with the ability to survive flooding for up to 14 days without significant productivity loss. TJF-Rawa 2 is better suited to shallow peatlands and can produce optimally even at soil acidity (pH) as low as 4.2 — conditions that typically severely limit plant growth.",
      "Trials show both varieties yielding between 3.5 and 4.8 tons per hectare on suboptimal land — a figure 60–80% higher than the local varieties typically grown by farmers in those areas. The formal registration process with the Plant Variety Protection and Agricultural Licensing Center has begun, and both varieties are expected to be available to farmers by the late 2026 planting season.",
    ],
  },
];

export const knowledgeTopicsEn = [
  {
    id: 1,
    title: "Food Security",
    slug: "food-security",
    icon: "🌾",
    count: 41,
    description: "A quarter of the world's population lacks regular access to healthy food. TJF examines the four pillars of food security — availability, access, utilization, and stability — to drive systemic transformation of Indonesia's food systems.",
    color: "green",
    searchKey: "food",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
  },
  {
    id: 2,
    title: "Agriculture",
    slug: "agriculture",
    icon: "🌱",
    count: 38,
    description: "Sustainable and innovative agricultural practices for Indonesia's tropical lands — from cultivation and water management techniques to empowering local farmers for environmentally friendly productivity.",
    color: "amber",
    searchKey: "agriculture",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
  },
  {
    id: 3,
    title: "Suboptimal Land",
    slug: "suboptimal-land",
    icon: "🌍",
    count: 34,
    description: "Suboptimal land is less fertile but still usable — too wet, dry, or acidic for conventional farming. TJF's research demonstrates its potential as a future food source for Indonesia.",
    color: "blue",
    searchKey: "suboptimal",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
  },
  {
    id: 4,
    title: "Livelihood",
    slug: "livelihood",
    icon: "👨‍🌾",
    count: 22,
    description: "Strengthening the capacity and welfare of local farming communities — from knowledge access and appropriate technology to economic empowerment based on the land they cultivate.",
    color: "purple",
    searchKey: "farmers",
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
  },
  {
    id: 5,
    title: "Landscape",
    slug: "landscape",
    icon: "🏞️",
    count: 27,
    description: "The Earth comprises different landscape types — urban, agricultural, and forest — each vital to human and ecosystem needs. TJF promotes integrated landscape management for sustainable natural resource use.",
    color: "teal",
    searchKey: "peatland",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
  },
  {
    id: 6,
    title: "Governance",
    slug: "governance",
    icon: "🏛️",
    count: 15,
    description: "Strong governance is key to food system transformation. TJF advocates for evidence-based, inclusive policies — connecting field research findings with national-level decision makers.",
    color: "red",
    searchKey: "policy",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
  },
];

export const statsEn = [
  { label: "Publications & Research", value: "150+", icon: "📄" },
  { label: "Active Projects",         value: "124+", icon: "🌱" },
  { label: "Provinces Reached",       value: "15",   icon: "📍" },
];

export const partnersEn = [
  { name: "Ministry of Agriculture RI",  logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Logo_Kementerian_Pertanian_Republik_Indonesia.svg/250px-Logo_Kementerian_Pertanian_Republik_Indonesia.svg.png" },
  { name: "BRIN",                        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Main_Logo_of_National_Research_and_Innovation_Agency_of_Indonesia.svg/200px-Main_Logo_of_National_Research_and_Innovation_Agency_of_Indonesia.svg.png" },
  { name: "IPB University",              logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/IPB_Logo.svg/200px-IPB_Logo.svg.png" },
  { name: "CGIAR",                       logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/CGIAR-logo.svg/250px-CGIAR-logo.svg.png" },
  { name: "GIZ Indonesia",               logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Deutsche_Gesellschaft_f%C3%BCr_Internationale_Zusammenarbeit_Logo.svg/320px-Deutsche_Gesellschaft_f%C3%BCr_Internationale_Zusammenarbeit_Logo.svg.png" },
  { name: "Universitas Sriwijaya",       logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/92/UNSRI_Logo.png/250px-UNSRI_Logo.png" },
  { name: "FAO Indonesia",               logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/FAO_logo.svg/200px-FAO_logo.svg.png" },
  { name: "World Resources Institute",   logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/91/World_Resources_Institute_logo.svg/250px-World_Resources_Institute_logo.svg.png" },
];

export const researchFocusAreasEn = [
  {
    id: 1,
    slug: "peatland-agriculture-sustainability",
    icon: "🌿",
    color: "green",
    title: "Peatland Agriculture Sustainability",
    description: "This research focuses on sustainable agricultural practices in peatland areas, aiming to minimize environmental impact while maintaining productivity and food security.",
    stat: { publications: 34, years: "2018–2026" },
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    topics: ["suboptimal-land", "landscape", "agriculture"],
  },
  {
    id: 2,
    slug: "sustainable-food-system",
    icon: "🌾",
    color: "amber",
    title: "Sustainable Food System",
    description: "We explore strategies to build a food system that is resilient, equitable, and environmentally friendly — from production to consumption.",
    stat: { publications: 41, years: "2019–2026" },
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
    topics: ["food-security", "agriculture", "governance"],
  },
  {
    id: 3,
    slug: "coconut-research-center",
    icon: "🥥",
    color: "blue",
    title: "Coconut Research Center",
    description: "A research initiative dedicated to improving coconut-based agriculture through innovation, sustainability, and empowering local farmers.",
    stat: { publications: 22, years: "2020–2026" },
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80",
    topics: ["agriculture", "livelihood", "landscape"],
  },
  {
    id: 4,
    slug: "coastal-agriculture-water-management",
    icon: "💧",
    color: "teal",
    title: "Coastal Agriculture Water Management",
    description: "This research addresses water management challenges in coastal farming areas, promoting efficient use and climate resilience.",
    stat: { publications: 18, years: "2021–2026" },
    image: "https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800&q=80",
    topics: ["suboptimal-land", "landscape", "agriculture"],
  },
];

export const initiativeStoriesEn = [
  { id:1, slug:"hamparan-sayur-gambut-kalimantan", initiativeSlug:"pertanian-gambut-berkelanjutan", title:"Vegetable Fields on Kalimantan Peatland", date:"March 15, 2026", excerpt:"On peatland once considered unproductive, a farming community in Kapuas Hulu now harvests fresh vegetables every week thanks to TJF's support.", image:"https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80", location:"Borneo", landType:"Peatland", commodity:"Horticulture", content:["In Nanga Tayap Village, Ketapang Regency, West Kalimantan, 120 hectares of peatland that had been neglected for years has transformed into productive vegetable gardens. A community of 63 farmers in the Gambut Lestari Farmer Group has proven that properly managed peat can be a sustainable livelihood.","TJF's accompaniment program began in 2023, focusing on introducing eco-friendly peatland farming systems that prioritize ecosystem balance. Farmers were trained in precision water management techniques using micro-canals and simple water gates that allow them to independently regulate groundwater levels. As a result, production of water spinach, spinach, and eggplant tripled within one growing season.","Pak Dayat, the local farmer group leader, shared that the biggest change was not just in productivity but in how farmers view peatland. 'We used to think peat was dead land. Now it is our livelihood,' he said while pointing to the green expanse behind his home. TJF is now supporting replication of this model in three other peat villages in West Kalimantan."] },
  { id:2, slug:"petani-gambut-mandiri-jambi", initiativeSlug:"pertanian-gambut-berkelanjutan", title:"Independent Peat Farmers in Tanjung Jabung", date:"February 2, 2026", excerpt:"After two years of accompaniment, 45 peat farmers in East Tanjung Jabung can now manage their land independently without relying on slash-and-burn practices.", image:"https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80", location:"Sumatra", landType:"Peatland", commodity:"Food Crops", content:["For decades, peat farmers in East Tanjung Jabung, Jambi, relied on slash-and-burn land clearing before planting season. This practice not only damaged the peat ecosystem but also contributed significantly to carbon emissions. Since 2024, TJF introduced a gradual transformation program replacing burning with composting and organic mulching methods.","The change process was not easy. TJF's field team spent the first three months simply building trust and listening to farmers' concerns. 'The hardest part was convincing senior farmers that the new methods would not reduce their harvest,' recalled Rina, TJF's field coordinator in Jambi.","Two growing seasons after the program started, the results speak for themselves. Average rice yields for adopting farmers increased 28% compared to before, while production costs fell 35%. Most importantly, not a single land fire occurred in the program area throughout the 2025 dry season — an unprecedented record."] },
  { id:3, slug:"kebun-nanas-gambut-riau", initiativeSlug:"pertanian-gambut-berkelanjutan", title:"Organic Pineapple Gardens on Riau Peat", date:"January 18, 2026", excerpt:"Pineapple farmers in Pelalawan Regency prove that high-value fruit commodities can be cultivated on peatland without destroying it.", image:"https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=800&q=80", location:"Sumatra", landType:"Peatland", commodity:"Seasonal Crops", content:["Pelalawan pineapple has long been known as one of Indonesia's best — sweet, fresh, and large. But farmers faced a dilemma: to increase production, they often had to open new peatland, which meant destroying the ecosystem. TJF and the Pelalawan Agriculture Office developed an intensification model that allows production to increase without land expansion.","The key innovation is an organic raised bed system planted on peat that remains moist. This technique allows pineapple roots to obtain optimal nutrition without direct contact with acidic peat. Combined with simple drip irrigation, farmers can save up to 60% water compared to conventional systems.","In the first harvest season using the new method, the Nanas Jaya Farmer Group produced 8.4 tons of pineapple per hectare — a 45% increase. 'This is not just about growing pineapples. It's about the future of our children and their forests,' said Pak Slamet, one of the program's pioneer farmers."] },
  { id:4, slug:"hamparan-sawah-indah-samarinda", initiativeSlug:"pertanian-lahan-suboptimal", title:"Beautiful Rice Fields at the Edge of Samarinda", date:"April 11, 2025", excerpt:"The story of Bu Sri Wagiyem, a farmer from Samarinda who has been practicing wetland farming using organic methods for 24 years, harvesting 1,700 kg of wet grain per season.", image:"https://images.unsplash.com/photo-1536408157428-1e2ede34fef3?w=800&q=80", location:"Borneo", landType:"Wetland", commodity:"Food Crops", content:["In a corner of Samarinda bordering wetlands, Bu Sri Wagiyem has kept her rice field productive for 24 years. No chemical fertilizers, no synthetic pesticides — only local wisdom passed down through generations, refined with technical guidance from TJF's team. Each harvest season, Bu Sri harvests about 1,700 kg of wet grain from her one-hectare plot.","The biggest challenge of farming in urban wetlands is unpredictable water level fluctuations. The rainy season brings flooding; the dry season makes the soil crack. Together with TJF, Bu Sri built a simple micro-drainage system from bamboo and local timber that naturally regulates water flow. The cost was almost zero, yet its effectiveness far surpassed permanent irrigation systems previously built by the government.","'The key is knowing the land like knowing an old friend,' said Bu Sri while showing the soil texture in her hands. Her story has become a replication model for 12 other farmers in Samarinda's wetland area. TJF documented her knowledge in a practical illustrated guide printed in local language and distributed to farming communities across East Kalimantan."] },
  { id:5, slug:"rawa-jadi-ladang-hortikultura", initiativeSlug:"pertanian-lahan-suboptimal", title:"Swamps Turned into Horticulture Fields in OKI", date:"March 20, 2025", excerpt:"Farmers in Ogan Komering Ilir prove that tidal swamp land can produce high-value vegetables supplying the Palembang market.", image:"https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=800&q=80", location:"Sumatra", landType:"Swamp Land", commodity:"Horticulture", content:["Ogan Komering Ilir (OKI) in South Sumatra has thousands of hectares of tidal swamp land long considered unproductive. But for Pak Herman and 38 members of the Rawa Makmur Farmer Group, this undervalued land has become their main income source, supplying fresh vegetables daily to major markets in Palembang.","TJF introduced floating bed techniques — planting platforms floating on swamp water using bamboo frames and thick compost layers. Various vegetables such as water spinach, mustard greens, and watercress grow abundantly year-round, unaffected by water level changes. In six months, the farmer group's turnover reached Rp 180 million from vegetable sales.","'We used to be embarrassed to say we were swamp farmers. Now we're proud,' said Pak Herman. The group now receives study visits from farmers in three other districts in South Sumatra."] },
  { id:6, slug:"inovasi-lahan-kering-ntt", initiativeSlug:"pertanian-lahan-suboptimal", title:"Doubled Harvests on NTT Dryland", date:"February 5, 2025", excerpt:"Amid drought threatening NTT's food security, water conservation techniques and adaptive local varieties help farmers in South Central Timor double their harvests.", image:"https://images.unsplash.com/photo-1559715745-e1b33a271c8f?w=800&q=80", location:"Lesser Sunda Islands", landType:"Dryland", commodity:"Food Crops", content:["South Central Timor (TTS), East Nusa Tenggara, regularly faces drought and food insecurity threats. Rainfall of only 4-5 months per year makes conventional farming almost impossible in the dry season. Since mid-2024, TJF's program has given farmers in Boti Village new strategies to face drought.","The program combines three approaches: biopore and micro-embung creation for rainwater storage, introduction of local sorghum and corn varieties adapted over hundreds of years to NTT's dry conditions, and thick organic mulching to minimize soil evaporation.","In the first planting season using the new approach, corn productivity increased from an average of 1.2 tons/ha to 2.8 tons/ha. 'For the first time in 30 years we don't need to move livestock to the mountains during the dry season,' said Mama Rosita, a senior farmer in Boti Village."] },
  { id:7, slug:"petani-jadi-penulis", initiativeSlug:"kolaborasi-menulis", title:"Farmers Become Writers: Documenting Local Wisdom", date:"May 10, 2026", excerpt:"TJF's writing residency program helped 15 farmers from Kalimantan and Sulawesi document their local farming knowledge into accessible guides.", image:"https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80", location:"Borneo", landType:"Wetland", commodity:"Horticulture", content:["Local farming knowledge passed down for hundreds of years faces extinction because it has never been documented. TJF's Farmer-Writer Residency Program aims to change this. Over three months, 15 selected farmers from Kalimantan and Sulawesi participate in an intensive program equipping them with writing, documentation, and publication skills.","The result is 15 mini-guides on local farming practices — from seedling transplanting techniques in peatland to reading natural signs to predict weather. All guides are published digitally and freely, and in print format distributed to village libraries and extension offices in both provinces.","'This is the first time I realized my water management method in the rice field is unique. A friend from Sulawesi said they'd never seen it before,' said Pak Asep from Central Kalimantan."] },
  { id:8, slug:"seri-buku-gambut-produktif", initiativeSlug:"kolaborasi-menulis", title:"Productive Peatland Book Series: From Research to Farmers' Shelves", date:"April 22, 2026", excerpt:"TJF publishes a popular book series on peatland farming, translating scientific research results into language farmers can easily understand.", image:"https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&q=80", location:"Sumatra", landType:"Peatland", commodity:"Seasonal Crops", content:["The gap between scientific knowledge and farmers' field practices has long hindered agricultural innovation adoption in Indonesia. TJF's Productive Peatland Book Series bridges this gap with five titles covering different aspects of peatland farming: water management, commodity selection, organic fertilization, pest control, and marketing.","In the first two months after launch, more than 8,000 physical copies were distributed to farmer groups and extension offices in Riau, Jambi, Central Kalimantan, and West Kalimantan. The digital version was downloaded more than 15,000 times.","'This is the first farming book I actually read to the end,' commented one farmer in a program evaluation session."] },
  { id:9, slug:"dialog-petani-pembuat-kebijakan", initiativeSlug:"kolaborasi-menulis", title:"Open Dialogue: Farmers Speak Directly with Policymakers", date:"March 8, 2026", excerpt:"TJF's quarterly dialogue forum connects peat farmers with Agriculture Ministry officials and parliament members to discuss regulations affecting their farming.", image:"https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80", location:"Sulawesi", landType:"Wetland", commodity:"Food Crops", content:["Agricultural policy is often made without sufficiently involving those most affected: farmers. TJF fills this gap through the Farmer-Policymaker Dialogue Forum held quarterly. The forum brings together 20 farmer representatives from various regions with Agriculture Ministry officials, House of Representatives Commission IV members, and agricultural academics in an equal discussion space.","The latest forum in Makassar produced a series of concrete recommendations on wetland use regulations in Sulawesi's coastal areas. Farmer representatives presented their direct experiences facing bureaucratic permit complexities.","Three months after the forum, one recommendation on simplifying farm credit documents is already being implemented in three districts in South Sulawesi as a pilot."] },
  { id:10, slug:"dashboard-ketahanan-pangan-daerah", initiativeSlug:"pusat-ketahanan-pangan", title:"Food Security Dashboard: Real-Time Data for Better Decisions", date:"June 1, 2026", excerpt:"TJF launches a regional food security dashboard enabling local governments to monitor food indicators in real-time and respond to threats before they become crises.", image:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80", location:"Sulawesi", landType:"Wetland", commodity:"Food Crops", content:["Food crises rarely come suddenly — there are usually early warning signs missed because data is unavailable or misread. TJF's Food Security Dashboard integrates production data, market prices, weather conditions, and storage capacity from 24 districts in four provinces into one interface easily readable by regional decision-makers.","The dashboard development involved agriculture and food security offices from four partner provinces — South Sulawesi, Central Sulawesi, South Kalimantan, and East Nusa Tenggara. Training was provided to 120 district-level agriculture staff.","In the first three months of operation, the system successfully detected potential rice supply shortages in two Central Sulawesi districts six weeks before a critical situation, allowing local governments to take preventive action."] },
  { id:11, slug:"jaringan-riset-multi-aktor", initiativeSlug:"pusat-ketahanan-pangan", title:"Multi-Actor Research Network: Universities, Farmers, and Government United", date:"May 14, 2026", excerpt:"Three agricultural universities, 8 farmer groups, and 4 agriculture offices join a collaborative research network coordinated by TJF to accelerate food innovation.", image:"https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&q=80", location:"Sulawesi", landType:"Wetland", commodity:"Food Crops", content:["Agricultural research in Indonesia has long operated in separate silos: universities produce knowledge that doesn't reach farmers, farmers innovate without shareable documentation, and governments make policies without sufficient field data. The Multi-Actor Research Network (MARN) coordinated by TJF breaks these silos.","MARN connects Hasanuddin University, Tadulako University, and IPB University with eight farmer groups from South and Central Sulawesi, plus four district agriculture offices. In the first year, MARN produced three field-tested land management protocols ready for broad application.","One protocol for integrated rice-fish farming in wetlands increases farmer income an average of 60% compared to rice monoculture."] },
  { id:12, slug:"advokasi-kebijakan-pangan-nasional", initiativeSlug:"pusat-ketahanan-pangan", title:"From Data to Policy: Advocating for National Food Systems", date:"April 28, 2026", excerpt:"TJF presented research-based policy recommendations to Bappenas and Parliament as input for the 2025-2030 National Medium-Term Development Plan in the food security cluster.", image:"https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80", location:"Borneo", landType:"Peatland", commodity:"Food Crops", content:["An 87-page document titled 'Indonesian Food System Policy Recommendations 2025-2030' prepared by TJF secured direct attention from Bappenas' Deputy for Food and Agribusiness. The document summarizes eight years of TJF's field research and offers 24 policy recommendations supported by data from 12 provinces.","The advocacy process involved a series of closed dialogues with key officials, farmer presentations as direct resource persons, and open seminars inviting media and civil society organizations.","Four of TJF's 24 recommendations were officially adopted as part of the 2025-2030 National Medium-Term Development Plan document ratified in late April 2026, including recommendations on national peatland management standards for agriculture and fiscal incentives for farmers adopting regenerative practices."] },
];
