export const publications = [
  {
    id: 1,
    slug: "krisis-nilai-tukar-ketahanan-pangan",
    title: "Krisis Nilai Tukar Indonesia sebagai Pengingat bagi Ketahanan Pangan",
    category: "Brief",
    date: "Juni 2026",
    description: "Analisis dampak krisis nilai tukar terhadap sistem ketahanan pangan nasional dan strategi adaptasi jangka pendek.",
    tags: ["ketahanan pangan", "kebijakan", "ekonomi"],
    image: "https://images.unsplash.com/photo-1611735341450-74d61e660ad2?w=600&q=80",
    researchAreas: ["sustainable-food-system"],
    topics: ["food-security", "governance"],
  },
  {
    id: 2,
    slug: "pengelolaan-air-gambut-kelapa-berkelanjutan",
    title: "Pengelolaan Air Tradisional di Lahan Gambut untuk Pertanian Kelapa Berkelanjutan",
    category: "Research Article",
    date: "Mei 2026",
    description: "Kajian praktik pengelolaan air lokal di lahan gambut Kalimantan yang mendukung pertanian kelapa berkelanjutan.",
    tags: ["lahan gambut", "air", "pertanian"],
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80",
    researchAreas: ["peatland-agriculture-sustainability", "coconut-research-center"],
    topics: ["suboptimal-land", "landscape", "agriculture"],
  },
  {
    id: 3,
    slug: "laporan-tahunan-2025-keberlanjutan-pangan",
    title: "Laporan Tahunan 2025: Jalur Kolaboratif Menuju Keberlanjutan Pangan",
    category: "Annual Report",
    date: "April 2026",
    description: "Laporan tahunan TJF 2025 yang merangkum capaian, pembelajaran, dan arah strategis organisasi.",
    tags: ["laporan tahunan", "organisasi"],
    image: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600&q=80",
    researchAreas: ["sustainable-food-system", "peatland-agriculture-sustainability", "coconut-research-center", "coastal-agriculture-water-management"],
    topics: ["food-security", "agriculture", "suboptimal-land", "livelihood", "landscape", "governance"],
  },
  {
    id: 4,
    slug: "potensi-lahan-rawa-pasang-surut",
    title: "Potensi Lahan Rawa Pasang Surut sebagai Sumber Pangan Masa Depan",
    category: "Research Article",
    date: "Maret 2026",
    description: "Penelitian mendalam tentang optimasi lahan rawa pasang surut di Sumatera Selatan untuk produksi padi.",
    tags: ["lahan rawa", "padi", "Sumatera"],
    image: "https://images.unsplash.com/photo-1536408157428-1e2ede34fef3?w=600&q=80",
    researchAreas: ["coastal-agriculture-water-management"],
    topics: ["suboptimal-land", "food-security", "agriculture"],
  },
  {
    id: 5,
    slug: "panduan-pertanian-regeneratif-lahan-suboptimal",
    title: "Panduan Praktis Pertanian Regeneratif di Lahan Suboptimal",
    category: "Book",
    date: "Februari 2026",
    description: "Buku panduan komprehensif untuk petani dan penyuluh dalam menerapkan pertanian regeneratif di lahan marginal.",
    tags: ["pertanian regeneratif", "panduan", "petani"],
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80",
    researchAreas: ["sustainable-food-system"],
    topics: ["agriculture", "livelihood", "suboptimal-land"],
  },
  {
    id: 6,
    slug: "dampak-perubahan-iklim-lahan-gambut",
    title: "Dampak Perubahan Iklim terhadap Produktivitas Lahan Gambut di Indonesia",
    category: "Research Article",
    date: "Januari 2026",
    description: "Studi longitudinal dampak perubahan iklim pada produktivitas dan keberlanjutan pengelolaan lahan gambut.",
    tags: ["perubahan iklim", "gambut", "produktivitas"],
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&q=80",
    researchAreas: ["peatland-agriculture-sustainability"],
    topics: ["suboptimal-land", "landscape"],
  },
  {
    id: 7,
    slug: "inovasi-varietas-padi-adaptif",
    title: "Inovasi Varietas Padi Adaptif untuk Lahan Suboptimal",
    category: "Research Article",
    date: "Desember 2025",
    description: "Hasil pengembangan varietas padi yang adaptif terhadap kondisi lahan suboptimal dan perubahan iklim.",
    tags: ["varietas padi", "inovasi", "adaptasi"],
    image: "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=600&q=80",
    researchAreas: ["sustainable-food-system"],
    topics: ["agriculture", "food-security", "suboptimal-land"],
  },
  {
    id: 8,
    slug: "ekosistem-pengetahuan-ketahanan-pangan",
    title: "Ekosistem Pengetahuan untuk Ketahanan Pangan: Peran Knowledge Intermediary",
    category: "Brief",
    date: "November 2025",
    description: "Tinjauan peran organisasi perantara pengetahuan dalam membangun ekosistem ketahanan pangan yang berkelanjutan.",
    tags: ["pengetahuan", "ekosistem", "intermediary"],
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&q=80",
    researchAreas: ["sustainable-food-system"],
    topics: ["food-security", "governance"],
  },
];

export const initiatives = [
  {
    id: 1,
    title: "Pertanian Gambut Berkelanjutan",
    slug: "pertanian-gambut-berkelanjutan",
    tagline: "Mengembalikan fungsi gambut sebagai modal ekologis pangan",
    description: "Program ini mengembangkan model pertanian yang selaras dengan ekosistem gambut, menggabungkan kearifan lokal dan inovasi ilmiah untuk pertanian produktif sekaligus menjaga fungsi hidrologis gambut.",
    focus: ["Rewetting lahan gambut terdegradasi", "Pengembangan komoditas gambut ramah lingkungan", "Penguatan kelembagaan petani gambut"],
    color: "green",
    icon: "🌿",
    stats: { projects: 42, communities: 18, provinces: 5 },
    image: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80",
    topics: ["suboptimal-land", "landscape", "livelihood"],
  },
  {
    id: 2,
    title: "Pertanian Lahan Suboptimal",
    slug: "pertanian-lahan-suboptimal",
    tagline: "Mengoptimalkan potensi lahan marginal untuk masa depan pangan",
    description: "Inisiatif riset dan diseminasi yang mengeksplorasi potensi lahan-lahan suboptimal — rawa, pasang surut, lahan kering, dan lahan masam — sebagai sumber pangan masa depan melalui inovasi teknologi dan pendekatan partisipatif.",
    focus: ["Riset adaptasi tanaman di lahan suboptimal", "Pengembangan teknologi input rendah", "Diseminasi praktik terbaik pertanian lahan marginal"],
    color: "blue",
    icon: "🌾",
    stats: { projects: 35, communities: 24, provinces: 8 },
    image: "https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=800&q=80",
    topics: ["suboptimal-land", "agriculture", "food-security"],
  },
  {
    id: 3,
    title: "Kolaborasi Menulis",
    slug: "kolaborasi-menulis",
    tagline: "Membangun narasi bersama tentang masa depan pangan Indonesia",
    description: "Platform kolaborasi yang menghubungkan peneliti, praktisi lapangan, petani, dan pembuat kebijakan untuk bersama menghasilkan pengetahuan yang relevan dan dapat ditindaklanjuti.",
    focus: ["Program residensi penulis", "Seri webinar dan diskusi", "Penerbitan kolaboratif lintas aktor"],
    color: "amber",
    icon: "✍️",
    stats: { projects: 28, communities: 60, provinces: 15 },
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    topics: ["governance", "livelihood", "food-security"],
  },
  {
    id: 4,
    title: "Pusat Ketahanan dan Keberlanjutan Pangan",
    slug: "pusat-ketahanan-pangan",
    tagline: "Menjembatani riset dan kebijakan untuk sistem pangan yang tangguh",
    description: "Hub pengetahuan yang menghubungkan data riset, pembelajaran lapangan, dan analisis kebijakan untuk mendorong transformasi sistem pangan Indonesia menuju ketahanan jangka panjang.",
    focus: ["Analisis dan advokasi kebijakan pangan", "Pemantauan dan evaluasi sistem pangan", "Jaringan pengetahuan multi-stakeholder"],
    color: "blue",
    icon: "🏛️",
    stats: { projects: 19, communities: 40, provinces: 12 },
    image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&q=80",
    topics: ["food-security", "governance"],
  },
];

export const newsItems = [
  {
    id: 1,
    slug: "tjf-luncurkan-platform-digital-lahan-suboptimal",
    tags: ["platform digital", "lahan suboptimal", "teknologi", "pengetahuan"],
    title: "TJF Luncurkan Platform Digital Pengetahuan Lahan Suboptimal",
    category: "Berita Organisasi",
    date: "10 Juni 2026",
    excerpt: "Tay Juhana Foundation resmi meluncurkan platform digital terpadu sebagai pusat pengetahuan lahan suboptimal yang dapat diakses oleh seluruh pemangku kepentingan.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    topics: ["suboptimal-land", "governance"],
    content: [
      "Tay Juhana Foundation (TJF) pada 10 Juni 2026 resmi meluncurkan platform digital terpadu yang menjadi pusat pengetahuan lahan suboptimal pertama di Indonesia. Platform ini mengintegrasikan ribuan dokumen riset, panduan praktis lapangan, dan database kebijakan yang dapat diakses secara gratis oleh peneliti, petani, penyuluh, dan pembuat kebijakan di seluruh nusantara.",
      "Platform ini dikembangkan selama dua tahun bersama mitra teknologi lokal dan memuat lebih dari 500 publikasi ilmiah, 120 video tutorial pertanian, serta fitur konsultasi daring dengan para ahli TJF. Fitur utama platform mencakup sistem rekomendasi berbasis lokasi geografis yang membantu petani menemukan praktik terbaik sesuai kondisi lahan dan iklim di daerahnya.",
      "Menurut Direktur Program TJF, peluncuran ini merupakan bagian dari komitmen jangka panjang untuk mendemokratisasi akses pengetahuan pertanian. \"Kami ingin memastikan bahwa petani di pelosok Kalimantan memiliki akses yang sama terhadap ilmu pengetahuan dengan para peneliti di kota besar,\" ujarnya dalam sambutan peluncuran. Platform ini ditargetkan dapat melayani 50.000 pengguna aktif dalam tahun pertama operasinya.",
    ],
  },
  {
    id: 2,
    slug: "riset-tjf-diadopsi-kebijakan-pertanian-nasional",
    tags: ["kebijakan", "riset", "gambut", "pertanian nasional"],
    title: "Hasil Riset TJF Diadopsi dalam Kebijakan Pertanian Nasional",
    category: "Dampak",
    date: "28 Mei 2026",
    excerpt: "Kementerian Pertanian RI mengadopsi rekomendasi dari riset TJF tentang pengelolaan lahan gambut dalam penyusunan kebijakan pertanian nasional 2026-2030.",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    topics: ["governance", "agriculture", "suboptimal-land"],
    content: [
      "Dalam tonggak bersejarah bagi dunia riset pertanian Indonesia, Kementerian Pertanian Republik Indonesia secara resmi mengadopsi serangkaian rekomendasi kebijakan yang dihasilkan dari penelitian delapan tahun Tay Juhana Foundation tentang pengelolaan lahan gambut. Keputusan ini tertuang dalam Peraturan Menteri Pertanian yang diterbitkan pada akhir Mei 2026.",
      "Rekomendasi yang diadopsi mencakup standar pengelolaan air di lahan gambut, protokol penanaman komoditas ramah gambut, serta mekanisme insentif bagi petani yang menerapkan praktik pertanian berkelanjutan. TJF telah melakukan kajian mendalam di lima provinsi dengan ekosistem gambut terluas — Kalimantan Tengah, Kalimantan Barat, Riau, Jambi, dan Papua Barat — selama periode 2018 hingga 2025.",
      "Dampak kebijakan ini diperkirakan menyentuh lebih dari 4,2 juta hektare lahan gambut yang dikelola petani dan koperasi pertanian. Kepala Badan Riset dan Pengembangan Kementan menyatakan bahwa kolaborasi antara lembaga think tank independen seperti TJF dan kementerian adalah model yang perlu direplikasi di sektor-sektor lain. TJF berkomitmen untuk mendampingi implementasi kebijakan ini melalui program pelatihan dan monitoring lapangan.",
    ],
  },
  {
    id: 3,
    slug: "workshop-nasional-inovasi-pertanian-lahan-suboptimal-2026",
    tags: ["workshop", "inovasi", "lahan suboptimal", "komunitas"],
    title: "Workshop Nasional: Inovasi Pertanian Lahan Suboptimal 2026",
    category: "Kegiatan",
    date: "15 Mei 2026",
    excerpt: "TJF menyelenggarakan workshop nasional yang mempertemukan 200 peneliti, petani, dan pembuat kebijakan dari 15 provinsi untuk berbagi inovasi pertanian lahan suboptimal.",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    topics: ["suboptimal-land", "agriculture", "livelihood"],
    content: [
      "Selama tiga hari penuh, 15–17 Mei 2026, gedung konferensi di Jakarta menjadi pusat pertemuan lebih dari 200 peserta dari 15 provinsi dalam Workshop Nasional Inovasi Pertanian Lahan Suboptimal yang diselenggarakan oleh Tay Juhana Foundation. Acara ini menjadi forum terbesar yang pernah diadakan TJF dan menghadirkan perpaduan unik antara peneliti akademis, petani inovatif, penyuluh lapangan, dan pemangku kebijakan.",
      "Sesi unggulan workshop mencakup demonstrasi langsung teknologi pertanian presisi untuk lahan rawa pasang surut, diskusi kelompok tentang adaptasi varietas tanaman terhadap kondisi lahan marginal, serta sesi pitch inovasi di mana 20 petani mempresentasikan solusi kreatif mereka langsung kepada panel investor dan pembuat kebijakan. Empat dari 20 inovasi tersebut mendapatkan komitmen pendanaan awal untuk pengembangan lebih lanjut.",
      "Kepala Dinas Pertanian Kalimantan Selatan yang hadir sebagai pembicara kunci menyoroti pentingnya forum seperti ini dalam mempercepat transfer pengetahuan dari laboratorium ke lapangan. Workshop ditutup dengan penandatanganan nota kesepahaman antara TJF dengan tiga universitas pertanian untuk program penelitian kolaboratif selama lima tahun ke depan.",
    ],
  },
  {
    id: 4,
    slug: "petani-gambut-kalimantan-peningkatan-hasil-40-persen",
    tags: ["gambut", "kalimantan", "produktivitas", "pengelolaan air"],
    title: "Petani Gambut Kalimantan Raih Peningkatan Hasil 40% dengan Metode TJF",
    category: "Cerita Dampak",
    date: "2 Mei 2026",
    excerpt: "Komunitas petani gambut di Kalimantan Tengah berhasil meningkatkan hasil panen hingga 40% setelah menerapkan metode pertanian berkelanjutan yang dikembangkan TJF.",
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
    topics: ["suboptimal-land", "livelihood", "landscape", "food-security"],
    content: [
      "Di desa Sei Ahas, Kabupaten Kapuas, Kalimantan Tengah, Pak Suroso dan 47 petani tetangganya kini memanen padi dua kali setahun — sesuatu yang mereka anggap mustahil tiga tahun lalu. Berkat pendampingan intensif dari tim lapangan Tay Juhana Foundation sejak 2023, komunitas ini berhasil meningkatkan hasil panen rata-rata dari 2,1 ton per hektare menjadi 2,9 ton — peningkatan hampir 40%.",
      "Kunci keberhasilan ini terletak pada perubahan sistem pengelolaan air yang dikembangkan TJF. Metode \"water table management\" yang disesuaikan dengan kondisi gambut tropis Kalimantan memungkinkan petani menjaga tinggi muka air tanah di level optimal — cukup basah untuk mencegah kebakaran gambut, namun cukup kering untuk memungkinkan pertumbuhan tanaman yang sehat. Sistem ini dilengkapi dengan stasiun pemantauan sederhana yang dioperasikan petani sendiri.",
      "\"Dulu kami takut lahan gambut terbakar setiap kemarau. Sekarang kami punya kontrol,\" ujar Pak Suroso. Selain peningkatan produktivitas, komunitas ini juga melaporkan penurunan biaya produksi sebesar 25% karena penggunaan pupuk kimia yang lebih efisien. TJF berencana mereplikasi model ini di 12 desa gambut lainnya di Kalimantan Tengah dan Kalimantan Selatan pada akhir 2026.",
    ],
  },
  {
    id: 5,
    slug: "tjf-rilis-panduan-pengelolaan-lahan-gambut",
    tags: ["panduan", "gambut", "petani", "publikasi"],
    title: "TJF Rilis Panduan Pengelolaan Lahan Gambut untuk Petani",
    category: "Publikasi",
    date: "20 April 2026",
    excerpt: "Panduan praktis pengelolaan lahan gambut yang ditulis dalam bahasa sederhana kini tersedia gratis untuk diunduh.",
    image: "https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?w=800&q=80",
    topics: ["suboptimal-land", "landscape", "livelihood"],
    content: [
      "Tay Juhana Foundation merilis panduan pengelolaan lahan gambut yang telah lama ditunggu-tunggu komunitas pertanian Indonesia. Dokumen setebal 84 halaman ini ditulis dalam bahasa Indonesia yang mudah dipahami — jauh dari jargon akademis — dan dilengkapi dengan ilustrasi berwarna serta foto-foto lapangan yang mempermudah pemahaman petani yang mungkin memiliki keterbatasan literasi formal.",
      "Panduan ini mencakup enam area utama: pemahaman karakteristik lahan gambut, teknik pengukuran dan pengelolaan muka air tanah, pemilihan komoditas yang tepat, jadwal tanam yang optimal, penanganan hama dan penyakit spesifik gambut, serta langkah-langkah pencegahan kebakaran. Setiap bab dilengkapi dengan \"daftar periksa praktis\" yang dapat langsung digunakan petani di lapangan.",
      "Panduan ini tersedia dalam versi cetak yang dapat dipesan gratis melalui kantor Dinas Pertanian di 12 kabupaten mitra TJF, serta versi digital yang dapat diunduh melalui platform digital TJF. Dalam dua minggu pertama peluncuran, panduan ini telah diunduh lebih dari 8.000 kali dan dipesan dalam format cetak oleh 230 kelompok tani di seluruh Indonesia.",
    ],
  },
  {
    id: 6,
    slug: "kolaborasi-tjf-brin-varietas-padi-adaptif",
    tags: ["varietas padi", "BRIN", "kolaborasi", "lahan suboptimal"],
    title: "Kolaborasi TJF dan BRIN Hasilkan Varietas Padi Adaptif",
    category: "Riset",
    date: "8 April 2026",
    excerpt: "Kerja sama antara TJF dan BRIN berhasil mengembangkan dua varietas padi baru yang adaptif terhadap kondisi lahan rawa.",
    image: "https://images.unsplash.com/photo-1559715745-e1b33a271c8f?w=800&q=80",
    topics: ["agriculture", "food-security", "suboptimal-land"],
    content: [
      "Setelah empat tahun penelitian intensif, kolaborasi antara Tay Juhana Foundation dan Badan Riset dan Inovasi Nasional (BRIN) akhirnya membuahkan hasil: dua varietas padi baru yang secara khusus dikembangkan untuk kondisi lahan rawa dan pasang surut Indonesia. Kedua varietas ini — diberi nama \"TJF-Rawa 1\" dan \"TJF-Rawa 2\" — telah melalui serangkaian uji coba lapangan di Sumatera Selatan, Kalimantan Selatan, dan Sulawesi Selatan.",
      "TJF-Rawa 1 unggul dalam kondisi lahan dengan salinitas tinggi seperti yang ditemui di daerah pasang surut dekat pantai, dengan kemampuan bertahan dalam genangan air hingga 14 hari tanpa kehilangan produktivitas secara signifikan. TJF-Rawa 2 lebih cocok untuk lahan gambut dangkal dan mampu berproduksi optimal bahkan dengan tingkat keasaman tanah (pH) serendah 4,2 — kondisi yang biasanya sangat membatasi pertumbuhan tanaman.",
      "Uji coba menunjukkan kedua varietas ini menghasilkan antara 3,5 hingga 4,8 ton per hektare di lahan suboptimal — angka yang 60–80% lebih tinggi dari varietas lokal yang biasa ditanam petani di area tersebut. Proses registrasi resmi ke Pusat Perlindungan Varietas Tanaman dan Perizinan Pertanian telah dimulai, dan diharapkan kedua varietas dapat dipasarkan kepada petani pada musim tanam akhir 2026.",
    ],
  },
];

export const knowledgeTopics = [
  {
    id: 1,
    title: "Ketahanan Pangan",
    slug: "food-security",
    icon: "🌾",
    count: 41,
    description: "Seperempat populasi dunia tidak memiliki akses rutin terhadap pangan sehat. TJF mengkaji empat pilar ketahanan pangan — ketersediaan, akses, pemanfaatan, dan stabilitas — untuk mendorong transformasi sistem pangan Indonesia dari hulu ke hilir.",
    color: "green",
    searchKey: "pangan",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
  },
  {
    id: 2,
    title: "Pertanian",
    slug: "agriculture",
    icon: "🌱",
    count: 38,
    description: "Praktik pertanian berkelanjutan dan inovatif untuk lahan tropis Indonesia — dari teknik budidaya, pengelolaan air, hingga pemberdayaan petani lokal untuk produktivitas yang ramah lingkungan.",
    color: "amber",
    searchKey: "pertanian",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
  },
  {
    id: 3,
    title: "Lahan Suboptimal",
    slug: "suboptimal-land",
    icon: "🌍",
    count: 34,
    description: "Lahan suboptimal adalah lahan yang kurang subur namun masih bisa dimanfaatkan — terlalu basah, kering, atau asam untuk pertanian konvensional. Riset TJF membuktikan potensinya sebagai sumber pangan masa depan Indonesia.",
    color: "blue",
    searchKey: "suboptimal",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
  },
  {
    id: 4,
    title: "Penghidupan",
    slug: "livelihood",
    icon: "👨‍🌾",
    count: 22,
    description: "Penguatan kapasitas dan kesejahteraan komunitas petani lokal — dari akses pengetahuan, teknologi tepat guna, hingga pemberdayaan ekonomi berbasis potensi lahan yang mereka kelola.",
    color: "purple",
    searchKey: "petani",
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
  },
  {
    id: 5,
    title: "Lanskap",
    slug: "landscape",
    icon: "🏞️",
    count: 27,
    description: "Bumi terdiri dari berbagai tipe lanskap — perkotaan, pertanian, dan hutan — yang vital bagi manusia dan ekosistem. TJF mendorong pengelolaan lanskap terpadu untuk pemanfaatan sumber daya alam yang berkelanjutan.",
    color: "teal",
    searchKey: "gambut",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
  },
  {
    id: 6,
    title: "Tata Kelola",
    slug: "governance",
    icon: "🏛️",
    count: 15,
    description: "Kebijakan dan tata kelola yang kuat adalah kunci transformasi sistem pangan. TJF mengadvokasi regulasi berbasis bukti yang inklusif — menghubungkan temuan riset lapangan dengan pengambil keputusan di level nasional.",
    color: "red",
    searchKey: "kebijakan",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
  },
];

export const initiativeStories = [
  // ── Pertanian Gambut Berkelanjutan ──────────────────
  {
    id: 1,
    slug: "hamparan-sayur-gambut-kalimantan",
    tags: ["gambut", "hortikultura", "kalimantan", "pengelolaan air", "sayuran"],
    initiativeSlug: "pertanian-gambut-berkelanjutan",
    title: "Hamparan Sayur di Gambut Kalimantan",
    date: "15 Maret 2026",
    excerpt: "Di atas gambut yang dulu dianggap tak produktif, komunitas petani di Kapuas Hulu kini memanen aneka sayuran segar setiap minggu berkat pendampingan TJF.",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
    location: "Kalimantan",
    landType: "Lahan Gambut",
    commodity: "Hortikultura",
    content: [
      "Di Desa Nanga Tayap, Kabupaten Ketapang, Kalimantan Barat, lahan gambut seluas 120 hektare yang selama bertahun-tahun terbengkalai kini telah berubah menjadi hamparan kebun sayur yang produktif. Komunitas 63 petani yang tergabung dalam Kelompok Tani Gambut Lestari berhasil membuktikan bahwa gambut yang dikelola dengan benar dapat menjadi sumber penghidupan yang berkelanjutan.",
      "Program pendampingan TJF dimulai pada 2023 dengan fokus pada pengenalan sistem pertanian gambut ramah lingkungan yang mengedepankan keseimbangan ekosistem. Petani dilatih teknik pengelolaan air presisi menggunakan kanal mikro dan pintu air sederhana yang memungkinkan mereka mengatur tinggi muka air tanah secara mandiri. Hasilnya, produksi kangkung, bayam, dan terong meningkat tiga kali lipat dalam satu musim tanam.",
      "Pak Dayat, ketua kelompok tani setempat, mengungkapkan bahwa perubahan terbesar bukan hanya pada produktivitas, tetapi juga pada cara pandang petani terhadap lahan gambut. \"Dulu kami pikir gambut itu lahan mati. Sekarang ini ladang rezeki kami,\" ujarnya sambil menunjuk hamparan hijau yang membentang di belakang rumahnya. TJF kini mendampingi replikasi model ini di tiga desa gambut lainnya di Kalimantan Barat.",
    ],
  },
  {
    id: 2,
    slug: "petani-gambut-mandiri-jambi",
    tags: ["gambut", "jambi", "tanaman pangan", "komposting", "kebakaran lahan"],
    initiativeSlug: "pertanian-gambut-berkelanjutan",
    title: "Petani Gambut Mandiri di Tanjung Jabung",
    date: "2 Februari 2026",
    excerpt: "Setelah dua tahun pendampingan, 45 petani gambut di Tanjung Jabung Timur kini mampu mengelola lahan mereka secara mandiri tanpa bergantung pada pertanian bakar.",
    image: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80",
    location: "Sumatera",
    landType: "Lahan Gambut",
    commodity: "Tanaman Pangan",
    content: [
      "Selama puluhan tahun, petani gambut di Tanjung Jabung Timur, Jambi, bergantung pada praktik bakar lahan untuk membersihkan kebun sebelum musim tanam. Praktik ini tidak hanya merusak ekosistem gambut, tetapi juga menjadi penyumbang emisi karbon yang signifikan. Sejak 2024, TJF hadir dengan program transformasi bertahap yang menggantikan praktik bakar dengan metode komposting dan mulsa organik.",
      "Proses perubahan tidak mudah. Tim lapangan TJF menghabiskan tiga bulan pertama hanya untuk membangun kepercayaan dan mendengarkan kekhawatiran petani. \"Yang paling susah adalah meyakinkan petani senior bahwa cara baru ini tidak akan mengurangi hasil panen mereka,\" kenang Rina, koordinator lapangan TJF di Jambi. Pelatihan dilakukan secara berkelompok dengan demonstrasi langsung di lahan percontohan milik anggota yang bersedia mencoba lebih dulu.",
      "Dua musim tanam setelah program dimulai, hasilnya berbicara sendiri. Rata-rata hasil panen padi petani yang mengadopsi metode baru meningkat 28% dibanding sebelumnya, sementara biaya produksi turun 35% karena penggunaan pupuk kimia yang jauh berkurang. Yang lebih menggembirakan, tidak ada satu pun kejadian kebakaran lahan di wilayah program sepanjang musim kemarau 2025 — rekor yang belum pernah terjadi sebelumnya.",
    ],
  },
  {
    id: 3,
    slug: "kebun-nanas-gambut-riau",
    tags: ["gambut", "riau", "nanas", "organik", "intensifikasi"],
    initiativeSlug: "pertanian-gambut-berkelanjutan",
    title: "Kebun Nanas Organik di Atas Gambut Riau",
    date: "18 Januari 2026",
    excerpt: "Petani nanas di Kabupaten Pelalawan membuktikan bahwa komoditas buah bernilai tinggi bisa dibudidayakan di gambut tanpa merusaknya.",
    image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=800&q=80",
    location: "Sumatera",
    landType: "Lahan Gambut",
    commodity: "Tanaman Musiman",
    content: [
      "Nanas Pelalawan sudah lama dikenal sebagai salah satu nanas terbaik di Indonesia — manis, segar, dan berukuran besar. Namun selama ini para petani menghadapi dilema: untuk meningkatkan produksi, mereka sering terpaksa membuka lahan gambut baru yang berarti merusak ekosistem. TJF bersama Dinas Pertanian Kabupaten Pelalawan mengembangkan model intensifikasi yang memungkinkan produksi meningkat tanpa ekspansi lahan.",
      "Kunci inovasinya adalah sistem raised bed berbahan organik yang ditanam di atas lapisan gambut yang tetap terjaga kelembapannya. Teknik ini memungkinkan akar nanas mendapatkan nutrisi optimal tanpa kontak langsung dengan lapisan gambut yang asam. Dikombinasikan dengan irigasi tetes sederhana, petani dapat menghemat air hingga 60% dibandingkan sistem irigasi konvensional.",
      "Dalam musim panen pertama menggunakan metode baru, Kelompok Tani Nanas Jaya berhasil memproduksi 8,4 ton nanas per hektare — meningkat 45% dari rata-rata sebelumnya. Lebih dari itu, sertifikasi organik yang kini sedang diproses akan membuka akses ke pasar premium dengan harga 2–3 kali lebih tinggi. \"Ini bukan hanya soal menanam nanas. Ini soal masa depan anak cucu kami dan hutannya,\" tutur Pak Slamet, salah satu petani pelopor program.",
    ],
  },

  // ── Pertanian Lahan Suboptimal ──────────────────────
  {
    id: 4,
    slug: "hamparan-sawah-indah-samarinda",
    tags: ["lahan basah", "padi", "kalimantan", "organik", "samarinda"],
    initiativeSlug: "pertanian-lahan-suboptimal",
    title: "Hamparan Sawah Indah di Pinggir Kota Samarinda",
    date: "11 April 2025",
    excerpt: "Kisah Bu Sri Wagiyem, petani dari Samarinda yang selama 24 tahun bergelut dengan pertanian lahan basah menggunakan metode organik dan berhasil panen 1.700 kg gabah per musim.",
    image: "https://images.unsplash.com/photo-1536408157428-1e2ede34fef3?w=800&q=80",
    location: "Kalimantan",
    landType: "Lahan Basah",
    commodity: "Tanaman Pangan",
    content: [
      "Di sudut Samarinda yang berbatasan dengan lahan basah, Bu Sri Wagiyem sudah 24 tahun menjaga sawahnya tetap produktif. Tidak ada pupuk kimia, tidak ada pestisida sintetis — hanya kearifan lokal yang diwariskan turun-temurun, disempurnakan dengan pendampingan teknis dari tim TJF. Setiap musim panen, Bu Sri memanen sekitar 1.700 kg gabah basah dari lahan seluas satu hektare miliknya.",
      "Tantangan terbesar bertani di lahan basah pinggiran kota adalah fluktuasi tinggi muka air yang tidak terduga. Musim hujan membawa banjir, kemarau membuat tanah mengering dan retak. Bersama tim TJF, Bu Sri membangun sistem drainase mikro sederhana dari bambu dan kayu lokal yang mampu mengatur aliran air secara alami. Biayanya hampir nol, namun efektivitasnya jauh melampaui sistem irigasi permanen yang pernah dibangun pemerintah.",
      "\"Kuncinya adalah mengenal lahan seperti mengenal teman lama,\" kata Bu Sri sambil memperlihatkan tekstur tanah di tangannya. Kisah Bu Sri kini menjadi model replikasi untuk 12 petani lain di kawasan lahan basah Samarinda. TJF mendokumentasikan pengetahuannya dalam sebuah panduan praktis bergambar yang dicetak dalam bahasa lokal dan disebarkan ke seluruh komunitas tani di Kalimantan Timur.",
    ],
  },
  {
    id: 5,
    slug: "rawa-jadi-ladang-hortikultura",
    tags: ["rawa", "hortikultura", "sumatera selatan", "bedengan apung"],
    initiativeSlug: "pertanian-lahan-suboptimal",
    title: "Rawa Berubah Jadi Ladang Hortikultura OKI",
    date: "20 Maret 2025",
    excerpt: "Petani di Ogan Komering Ilir membuktikan bahwa lahan rawa pasang surut bisa menghasilkan sayuran bernilai tinggi yang memasok pasar Palembang.",
    image: "https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=800&q=80",
    location: "Sumatera",
    landType: "Lahan Rawa",
    commodity: "Hortikultura",
    content: [
      "Ogan Komering Ilir (OKI) di Sumatera Selatan memiliki ribuan hektare lahan rawa pasang surut yang selama ini dianggap tidak produktif. Namun bagi Pak Herman dan 38 anggota Kelompok Tani Rawa Makmur, lahan yang selalu diremehkan itu kini telah menjadi sumber penghasilan utama yang memasok sayuran segar ke pasar-pasar besar di Palembang setiap harinya.",
      "TJF memperkenalkan teknik pembuatan bedengan apung — platform tanam yang mengambang di atas air rawa menggunakan rangka bambu dan lapisan kompos tebal. Di atas bedengan inilah aneka sayuran seperti kangkung, sawi, dan selada air tumbuh subur sepanjang tahun tanpa terpengaruh naik turunnya permukaan air. Teknologi sederhana ini telah digunakan secara tradisional di beberapa daerah Asia Tenggara dan TJF mengadaptasinya untuk kondisi rawa OKI.",
      "Dalam enam bulan pertama program, omset kelompok tani mencapai Rp 180 juta dari penjualan sayuran. Lebih dari sekadar angka, yang lebih berharga adalah kepercayaan diri yang tumbuh di komunitas ini. \"Kami dulu malu bilang kami petani rawa. Sekarang bangga,\" ujar Pak Herman. Kelompok ini kini menerima kunjungan belajar dari petani di tiga kabupaten lain di Sumatera Selatan.",
    ],
  },
  {
    id: 6,
    slug: "inovasi-lahan-kering-ntt",
    tags: ["lahan kering", "NTT", "sorgum", "jagung", "kekeringan"],
    initiativeSlug: "pertanian-lahan-suboptimal",
    title: "Panen Berlipat di Lahan Kering NTT",
    date: "5 Februari 2025",
    excerpt: "Di tengah kekeringan yang mengancam ketahanan pangan NTT, teknik konservasi air dan varietas lokal adaptif membantu petani Timor Tengah Selatan melipatgandakan panen.",
    image: "https://images.unsplash.com/photo-1559715745-e1b33a271c8f?w=800&q=80",
    location: "Kepulauan Kecil",
    landType: "Lahan Kering",
    commodity: "Tanaman Pangan",
    content: [
      "Timor Tengah Selatan (TTS), Nusa Tenggara Timur, adalah wilayah yang secara rutin menghadapi ancaman kekeringan dan kerawanan pangan. Curah hujan yang hanya turun 4–5 bulan dalam setahun membuat pertanian konvensional hampir mustahil di musim kemarau. Namun berkat program TJF yang dimulai pertengahan 2024, petani di Desa Boti dan sekitarnya kini memiliki strategi baru untuk menghadapi kekeringan.",
      "Program ini mengkombinasikan tiga pendekatan: pembuatan biopori dan embung skala mikro untuk menyimpan air hujan, pengenalan varietas sorgum dan jagung lokal yang telah teradaptasi selama ratusan tahun dengan kondisi kering NTT, serta teknik mulsa organik tebal untuk meminimalkan penguapan dari permukaan tanah. Semua teknologi ini berbasis pada sumber daya lokal yang tersedia dan dapat direplikasi tanpa biaya besar.",
      "Musim tanam pertama menggunakan pendekatan baru ini memberikan hasil yang mengejutkan. Produktivitas jagung meningkat dari rata-rata 1,2 ton/ha menjadi 2,8 ton/ha, sementara sorgum yang ditanam di lahan yang paling kering pun berhasil menghasilkan 1,5 ton/ha. Yang tidak kalah penting, ketersediaan air di embung-embung mikro memastikan ternak juga bisa melewati musim kering dengan kondisi lebih baik. \"Pertama kali dalam 30 tahun kami tidak perlu mengungsikan ternak ke gunung saat kemarau,\" kata Mama Rosita, petani senior di Desa Boti.",
    ],
  },

  // ── Kolaborasi Menulis ──────────────────────────────
  {
    id: 7,
    slug: "petani-jadi-penulis",
    tags: ["dokumentasi", "kearifan lokal", "residensi", "penulisan"],
    initiativeSlug: "kolaborasi-menulis",
    title: "Petani Jadi Penulis: Mendokumentasikan Kearifan Lokal",
    date: "10 Mei 2026",
    excerpt: "Program residensi menulis TJF membantu 15 petani dari Kalimantan dan Sulawesi mendokumentasikan pengetahuan pertanian lokal mereka dalam bentuk panduan yang bisa diakses semua orang.",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    location: "Kalimantan",
    landType: "Lahan Basah",
    commodity: "Hortikultura",
    content: [
      "Pengetahuan pertanian lokal yang telah diwariskan selama ratusan tahun terancam punah karena tidak pernah didokumentasikan. Program Residensi Petani-Penulis TJF hadir untuk mengubah situasi ini. Selama tiga bulan, 15 petani terpilih dari Kalimantan dan Sulawesi diundang mengikuti program intensif yang membekali mereka dengan kemampuan menulis, mendokumentasikan, dan mempublikasikan pengetahuan mereka.",
      "Peserta dibimbing oleh tim yang terdiri dari jurnalis pertanian, peneliti, dan editor berpengalaman. Namun yang lebih penting, setiap sesi menulis diawali dengan sesi berbagi di mana para petani saling mendengarkan kisah dan praktik masing-masing. \"Saya tidak tahu bahwa cara saya mengelola air di sawah itu ternyata unik. Teman dari Sulawesi bilang belum pernah lihat sebelumnya,\" ujar Pak Asep dari Kalimantan Tengah.",
      "Hasil program ini adalah 15 panduan mini tentang praktik pertanian lokal — mulai dari teknik transplantasi bibit di lahan gambut hingga cara membaca tanda-tanda alam untuk memperkirakan cuaca. Semua panduan diterbitkan secara digital dan gratis, serta dalam format cetak yang disebar ke perpustakaan desa dan balai penyuluhan di kedua provinsi. TJF berencana memperluas program ini ke 5 provinsi lain pada 2027.",
    ],
  },
  {
    id: 8,
    slug: "seri-buku-gambut-produktif",
    tags: ["buku", "gambut", "publikasi", "diseminasi", "petani"],
    initiativeSlug: "kolaborasi-menulis",
    title: "Seri Buku Gambut Produktif: Dari Riset ke Rak Buku Petani",
    date: "22 April 2026",
    excerpt: "TJF menerbitkan seri buku populer tentang pertanian gambut yang menerjemahkan hasil riset ilmiah ke dalam bahasa yang mudah dipahami petani.",
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&q=80",
    location: "Sumatera",
    landType: "Lahan Gambut",
    commodity: "Tanaman Musiman",
    content: [
      "Kesenjangan antara pengetahuan ilmiah dan praktik lapangan petani adalah masalah yang selama ini menghambat adopsi inovasi pertanian di Indonesia. Laporan ilmiah tentang gambut bertumpuk di perpustakaan universitas, sementara petani di lapangan tetap mengandalkan cara-cara lama yang tidak lagi optimal. Seri Buku Gambut Produktif TJF hadir untuk menjembatani kesenjangan ini.",
      "Seri ini terdiri dari lima judul yang masing-masing membahas aspek berbeda dari pertanian gambut: pengelolaan air, pemilihan komoditas, pemupukan organik, pengendalian hama, dan pemasaran hasil. Setiap buku ditulis oleh tim yang terdiri dari peneliti TJF dan petani praktisi, memastikan konten akurat secara ilmiah sekaligus relevan secara praktis. Ilustrasi langkah-demi-langkah menggantikan grafik dan tabel statistik yang biasa menghiasi publikasi akademis.",
      "Dalam dua bulan pertama setelah peluncuran, lebih dari 8.000 eksemplar buku fisik telah didistribusikan ke kelompok tani dan balai penyuluhan di Riau, Jambi, Kalimantan Tengah, dan Kalimantan Barat. Versi digitalnya diunduh lebih dari 15.000 kali. \"Ini pertama kalinya ada buku pertanian yang mau saya baca sampai habis,\" komentar seorang petani dalam sesi evaluasi program.",
    ],
  },
  {
    id: 9,
    slug: "dialog-petani-pembuat-kebijakan",
    tags: ["kebijakan", "dialog", "sulawesi", "regulasi", "advokasi"],
    initiativeSlug: "kolaborasi-menulis",
    title: "Dialog Terbuka: Petani Bicara Langsung dengan Pembuat Kebijakan",
    date: "8 Maret 2026",
    excerpt: "Forum dialog triwulanan TJF mempertemukan petani gambut dengan pejabat Kementan dan anggota DPR untuk membahas regulasi yang berdampak pada pertanian mereka.",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    location: "Sulawesi",
    landType: "Lahan Basah",
    commodity: "Tanaman Pangan",
    content: [
      "Kebijakan pertanian seringkali dibuat tanpa cukup melibatkan mereka yang paling terdampak: petani. TJF mengisi celah ini melalui Forum Dialog Petani-Pembuat Kebijakan yang diselenggarakan setiap kuartal. Forum ini mempertemukan 20 perwakilan petani dari berbagai wilayah dengan pejabat Kementerian Pertanian, anggota Komisi IV DPR RI, dan akademisi pertanian dalam satu ruang diskusi yang setara.",
      "Forum terbaru yang berlangsung di Makassar menghasilkan serangkaian rekomendasi konkret terkait regulasi penggunaan lahan basah di kawasan pesisir Sulawesi. Para petani memaparkan pengalaman langsung mereka menghadapi kerumitan birokrasi perizinan yang seringkali membuat mereka tidak bisa mengakses kredit pertanian. Respons dari pejabat Kementan lebih konstruktif dari yang diharapkan — dalam sesi terbuka, Direktur Jenderal Prasarana dan Sarana Pertanian berkomitmen untuk meninjau ulang prosedur perizinan yang bermasalah.",
      "Tiga bulan setelah forum, salah satu rekomendasi tentang simplifikasi dokumen kredit usaha tani sudah mulai diimplementasikan di tiga kabupaten di Sulawesi Selatan sebagai pilot. TJF mendokumentasikan setiap forum dan mempublikasikan ringkasan rekomendasi beserta status tindak lanjutnya secara terbuka di website, memastikan akuntabilitas dari semua pihak yang berkomitmen.",
    ],
  },

  // ── Pusat Ketahanan dan Keberlanjutan Pangan ────────
  {
    id: 10,
    slug: "dashboard-ketahanan-pangan-daerah",
    tags: ["dashboard", "data", "ketahanan pangan", "teknologi"],
    initiativeSlug: "pusat-ketahanan-pangan",
    title: "Dashboard Ketahanan Pangan: Data Real-Time untuk Keputusan Lebih Baik",
    date: "1 Juni 2026",
    excerpt: "TJF meluncurkan dashboard ketahanan pangan daerah yang memungkinkan pemda memantau indikator pangan secara real-time dan merespons ancaman sebelum menjadi krisis.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    location: "Sulawesi",
    landType: "Lahan Basah",
    commodity: "Tanaman Pangan",
    content: [
      "Krisis pangan jarang datang tiba-tiba — biasanya ada tanda-tanda peringatan dini yang terlewatkan karena data tidak tersedia atau tidak terbaca dengan tepat. Dashboard Ketahanan Pangan TJF dirancang untuk mengubah situasi ini. Platform digital ini mengintegrasikan data produksi pangan, harga pasar, kondisi cuaca, dan kapasitas penyimpanan dari 24 kabupaten di empat provinsi dalam satu antarmuka yang mudah dibaca oleh pengambil keputusan daerah.",
      "Pengembangan dashboard ini melibatkan dinas pertanian dan ketahanan pangan dari empat provinsi mitra — Sulawesi Selatan, Sulawesi Tengah, Kalimantan Selatan, dan Nusa Tenggara Timur. Keterlibatan pengguna sejak awal proses pengembangan memastikan bahwa fitur yang dibangun benar-benar menjawab kebutuhan praktis, bukan sekadar canggih secara teknis. Pelatihan penggunaan diberikan kepada 120 staf dinas pertanian di tingkat kabupaten.",
      "Dalam tiga bulan pertama operasi, sistem ini berhasil mendeteksi potensi kekurangan pasokan beras di dua kabupaten di Sulawesi Tengah enam minggu sebelum situasi kritis. Pemda setempat mampu mengambil tindakan preventif — mengaktifkan cadangan pangan daerah dan berkoordinasi dengan Bulog untuk distribusi tambahan — sehingga harga tidak melonjak dan masyarakat tidak merasakan dampak. Ini adalah bukti nyata bahwa data yang tepat waktu bisa mencegah krisis pangan.",
    ],
  },
  {
    id: 11,
    slug: "jaringan-riset-multi-aktor",
    tags: ["riset", "kolaborasi", "universitas", "sulawesi", "jaringan"],
    initiativeSlug: "pusat-ketahanan-pangan",
    title: "Jaringan Riset Multi-Aktor: Universitas, Petani, dan Pemerintah Bersatu",
    date: "14 Mei 2026",
    excerpt: "Tiga universitas pertanian, 8 kelompok tani, dan 4 dinas pertanian bergabung dalam jaringan riset kolaboratif yang dikoordinasikan TJF untuk mempercepat inovasi pangan.",
    image: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&q=80",
    location: "Sulawesi",
    landType: "Lahan Basah",
    commodity: "Tanaman Pangan",
    content: [
      "Riset pertanian di Indonesia selama ini berjalan dalam silos yang terpisah: universitas menghasilkan pengetahuan yang tidak sampai ke petani, petani berinovasi tanpa dokumentasi yang bisa dibagikan, dan pemerintah membuat kebijakan tanpa cukup data lapangan. Jaringan Riset Multi-Aktor (JRMA) yang dikoordinasikan TJF hadir untuk memecah silos ini.",
      "JRMA menghubungkan Universitas Hasanuddin, Universitas Tadulako, dan IPB University dengan delapan kelompok tani dari Sulawesi Selatan dan Tengah, serta empat dinas pertanian kabupaten. Setiap kuartal, semua anggota jaringan bertemu dalam sesi berbagi data dan temuan. Peneliti universitas mempresentasikan hasil riset terbaru; petani memaparkan tantangan lapangan yang butuh solusi segera; dinas pertanian menyampaikan prioritas kebijakan yang membutuhkan dukungan data.",
      "Dalam tahun pertama operasi, JRMA berhasil menghasilkan tiga protokol pengelolaan lahan yang telah diuji di lapangan dan siap diaplikasikan secara luas. Salah satunya adalah protokol penanaman padi-ikan terpadu di lahan basah yang meningkatkan pendapatan petani rata-rata 60% dibanding monokultur padi. TJF berperan sebagai sekretariat jaringan, memastikan komunikasi berjalan lancar dan komitmen masing-masing pihak terdokumentasi dan ditindaklanjuti.",
    ],
  },
  {
    id: 12,
    slug: "advokasi-kebijakan-pangan-nasional",
    tags: ["advokasi", "kebijakan", "RPJMN", "sistem pangan"],
    initiativeSlug: "pusat-ketahanan-pangan",
    title: "Dari Data ke Kebijakan: Advokasi Sistem Pangan Nasional",
    date: "28 April 2026",
    excerpt: "TJF mempresentasikan rekomendasi kebijakan berbasis riset kepada Bappenas dan DPR sebagai masukan untuk RPJMN 2025-2030 dalam klaster ketahanan pangan.",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    location: "Kalimantan",
    landType: "Lahan Gambut",
    commodity: "Tanaman Pangan",
    content: [
      "Satu dokumen setebal 87 halaman berjudul 'Rekomendasi Kebijakan Sistem Pangan Indonesia 2025-2030' yang disusun TJF berhasil mendapatkan perhatian langsung dari Deputi Bidang Pangan dan Agribisnis Bappenas. Dokumen ini merangkum delapan tahun penelitian lapangan TJF dan menawarkan 24 rekomendasi kebijakan yang didukung data dari 12 provinsi di Indonesia.",
      "Proses advokasi tidak hanya melibatkan penyerahan dokumen formal. Tim kebijakan TJF melakukan serangkaian dialog tertutup dengan para pejabat kunci, menghadirkan petani sebagai narasumber langsung, dan menyelenggarakan seminar terbuka yang mengundang media dan organisasi masyarakat sipil. Strategi multi-saluran ini memastikan rekomendasi TJF tidak hanya dibaca oleh pengambil keputusan tetapi juga mendapatkan dukungan publik yang luas.",
      "Empat dari 24 rekomendasi TJF secara resmi diadopsi sebagai bagian dari dokumen RPJMN 2025-2030 klaster ketahanan pangan yang disahkan pada akhir April 2026. Di antaranya adalah rekomendasi tentang penetapan standar nasional pengelolaan lahan gambut untuk pertanian dan insentif fiskal bagi petani yang mengadopsi praktik pertanian regeneratif. TJF berkomitmen memantau implementasi rekomendasi yang diadopsi dan mempublikasikan laporan perkembangan setiap enam bulan.",
    ],
  },
];

export const stats = [
  { label: "Publikasi & Riset",   value: "150+", icon: "📄" },
  { label: "Proyek Aktif",        value: "124+", icon: "🌱" },
  { label: "Provinsi Terjangkau", value: "15",   icon: "📍" },
];

export const partners = [
  { name: "Kementerian Pertanian RI",  logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Logo_Kementerian_Pertanian_Republik_Indonesia.svg/250px-Logo_Kementerian_Pertanian_Republik_Indonesia.svg.png" },
  { name: "BRIN",                      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Main_Logo_of_National_Research_and_Innovation_Agency_of_Indonesia.svg/200px-Main_Logo_of_National_Research_and_Innovation_Agency_of_Indonesia.svg.png" },
  { name: "IPB University",            logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/IPB_Logo.svg/200px-IPB_Logo.svg.png" },
  { name: "CGIAR",                     logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/CGIAR-logo.svg/250px-CGIAR-logo.svg.png" },
  { name: "GIZ Indonesia",             logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Deutsche_Gesellschaft_f%C3%BCr_Internationale_Zusammenarbeit_Logo.svg/320px-Deutsche_Gesellschaft_f%C3%BCr_Internationale_Zusammenarbeit_Logo.svg.png" },
  { name: "Universitas Sriwijaya",     logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/92/UNSRI_Logo.png/250px-UNSRI_Logo.png" },
  { name: "FAO Indonesia",             logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/FAO_logo.svg/200px-FAO_logo.svg.png" },
  { name: "World Resources Institute", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/91/World_Resources_Institute_logo.svg/250px-World_Resources_Institute_logo.svg.png" },
];

export const researchFocusAreas = [
  {
    id: 1,
    slug: "peatland-agriculture-sustainability",
    icon: "🌿",
    color: "green",
    title: "Keberlanjutan Pertanian Lahan Gambut",
    description: "Riset ini berfokus pada praktik pertanian berkelanjutan di lahan gambut, bertujuan meminimalkan dampak lingkungan sambil menjaga produktivitas dan ketahanan pangan.",
    stat: { publications: 34, years: "2018–2026" },
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    topics: ["suboptimal-land", "landscape", "agriculture"],
  },
  {
    id: 2,
    slug: "sustainable-food-system",
    icon: "🌾",
    color: "amber",
    title: "Sistem Pangan Berkelanjutan",
    description: "Kami mengeksplorasi strategi membangun sistem pangan yang tangguh, berkeadilan, dan ramah lingkungan — dari produksi hingga konsumsi.",
    stat: { publications: 41, years: "2019–2026" },
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
    topics: ["food-security", "agriculture", "governance"],
  },
  {
    id: 3,
    slug: "coconut-research-center",
    icon: "🥥",
    color: "blue",
    title: "Pusat Riset Kelapa",
    description: "Inisiatif riset yang didedikasikan untuk meningkatkan pertanian berbasis kelapa melalui inovasi, keberlanjutan, dan pemberdayaan petani lokal.",
    stat: { publications: 22, years: "2020–2026" },
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80",
    topics: ["agriculture", "livelihood", "landscape"],
  },
  {
    id: 4,
    slug: "coastal-agriculture-water-management",
    icon: "💧",
    color: "teal",
    title: "Manajemen Air Pertanian Pesisir",
    description: "Riset ini mengatasi tantangan pengelolaan air di kawasan pertanian pesisir, mendorong efisiensi penggunaan dan ketahanan iklim.",
    stat: { publications: 18, years: "2021–2026" },
    image: "https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800&q=80",
    topics: ["suboptimal-land", "landscape", "agriculture"],
  },
];
